spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security
    username: mysql
    password: mysql
  #    url: jdbc:postgresql://localhost:5432/spring-security
  #    username: postgres
  #    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
