spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security
    username: mysql
    password: mysql
  #    url: jdbc:postgresql://localhost:5432/spring-security
  #    username: postgres
  #    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak.com.au:8180/realms/spring-security-dev/protocol/openid-connect/certs
