create table users
(
    username varchar(50)  not null primary key,
    password varchar(500) not null,
    enabled  boolean      not null
);
create table authorities
(
    username  varchar(50) not null,
    authority varchar(50) not null,
    constraint fk_authorities_users foreign key (username) references users (username)
);
create unique index ix_auth_username on authorities (username, authority);

-- the above are the default tables defined in spring security for authentication


CREATE TABLE customer
(
    id    int          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email varchar(45)  NOT NULL,
    pwd   varchar(200) NOT NULL,
    role  varchar(45)  NOT NULL,
    PRIMARY KEY (id)
);

-- the above is the custom table defined as per our requirement
